import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from hmmlearn.hmm import GaussianHMM
import matplotlib.pyplot as plt
import warnings
import os

warnings.filterwarnings("ignore")

# =================================================================================
# 1. COMPOUND MARKET REGIME DEFINITION & DATA PREPARATION
# =================================================================================
# DEFINITION & REASONING (COMPOUND REGIMES):
# A "Market Regime" is a persistent macroeconomic or behavioral state of the financial 
# markets. Rather than defining regimes purely by a single metric (like volatility), 
# modern quantitative finance defines them as "compound" multidimensional states.
#
# Our HMM identifies regimes using four crucial daily dimensions:
#   1. SPY Return (Broad Market Drift): Is the general economy expanding or contracting?
#   2. QQQ Return (Tech-Sector Momentum): Is high-beta/growth outperforming?
#   3. VIX (Forward-Looking Fear): Implied volatility. High VIX indicates market panic.
#   4. Volume Ratio (Conviction): Price changes must be confirmed by volume. Bear market 
#      crashes feature massive volume spikes (capitulation).
#
# WIDELY USED REGIME CLASSIFICATIONS (Standard 2-State):
#   - Regime 0 (Risk-On / Bull): Positive drift, low/falling VIX, average volume.
#   - Regime 1 (Risk-Off / Bear): Negative drift, high/spiking VIX, spiking volume.
#
# ACADEMIC & PROFESSIONAL REFERENCES:
# 1. Ang, A., & Bekaert, G. (2002). "International Asset Allocation with Regime Shifts." 
#    Review of Financial Studies.
# 2. Hamilton, J. D. (1989). "A New Approach to the Economic Analysis of Nonstationary 
#    Time Series and the Business Cycle." Econometrica.
# 3. Kritzman, M., Page, S., & Turkington, D. (2012). "Regime Shifts: Implications 
#    for Dynamic Strategies." Financial Analysts Journal.
# =================================================================================

def get_macro_csv_path():
    """Helper to resolve the path for the macro dataset based on your VS Code workspace."""
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(current_dir))
    csv_path = os.path.join(project_root, 'Finance Data', 'Historical_Data_MACRO.csv')
    
    if not os.path.exists(csv_path):
        # Fallback
        csv_path = "Finance Data/Historical_Data_MACRO.csv"
    return csv_path

def load_and_prepare_compound_data():
    csv_path = get_macro_csv_path()
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Cannot find {csv_path}. Please run download_macro_data.py first!")
        
    print(f"Loading local macro data from {csv_path}...")
    df = pd.read_csv(csv_path)
    df['Date'] = pd.to_datetime(df['Date'], utc=True)
    
    # Calculate daily returns
    df['SPY_Return'] = df['SPY_Close'].pct_change()
    df['QQQ_Return'] = df['QQQ_Close'].pct_change()
    
    # Calculate Intraday Volatility (High - Low) / Open
    # This acts as our new internal "fear/variance" gauge to replace the VIX!
    df['SPY_Intraday_Vol'] = (df['SPY_High'] - df['SPY_Low']) / df['SPY_Open']
    df['QQQ_Intraday_Vol'] = (df['QQQ_High'] - df['QQQ_Low']) / df['QQQ_Open']
    
    # Calculate Volume Ratio (Today's Volume / 20-Day Moving Average of Volume)
    df['SPY_Volume_Ratio'] = df['SPY_Volume'] / df['SPY_Volume'].rolling(window=20).mean()
    
    # Drop NaNs generated by pct_change and rolling averages
    df = df.dropna().reset_index(drop=True)
    
    print("Fitting Multivariate Gaussian HMM for Compound Market Regimes...")
    # Add SPY_Intraday_Vol to the HMM to give it a volatility dimension
    X_hmm = df[['SPY_Return', 'QQQ_Return', 'SPY_Volume_Ratio', 'SPY_Intraday_Vol']].values
    
    hmm_model = GaussianHMM(n_components=2, covariance_type="full", n_iter=1000, random_state=42)
    hmm_model.fit(X_hmm)
    
    df['Target_Regime'] = hmm_model.predict(X_hmm)
    
    # Create input features for the neural networks
    df['SPY_Log_Return'] = np.log(df['SPY_Close'] / df['SPY_Close'].shift(1))
    df['QQQ_Log_Return'] = np.log(df['QQQ_Close'] / df['QQQ_Close'].shift(1))
    
    df = df.dropna().reset_index(drop=True)
    return df

# ==========================================
# 2. SEQUENCE CREATION & CHRONOLOGICAL SPLIT
# ==========================================

class TimeSeriesDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
        
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

def create_sequences_and_split(df, feature_cols, target_col, sequence_length=30):
    X, y, dates = [], [], []
    features = df[feature_cols].values
    targets = df[target_col].values
    date_array = df['Date'].values
    
    for i in range(len(features) - sequence_length):
        X.append(features[i:i+sequence_length])
        y.append(targets[i+sequence_length])
        dates.append(date_array[i+sequence_length])
        
    X, y, dates = np.array(X), np.array(y), pd.to_datetime(dates)
    
    train_mask = dates.year < 2018
    val_mask = (dates.year >= 2018) & (dates.year < 2020)
    test_mask = dates.year >= 2020
    
    return (X[train_mask], y[train_mask], dates[train_mask]), \
           (X[val_mask], y[val_mask], dates[val_mask]), \
           (X[test_mask], y[test_mask], dates[test_mask])

# ==========================================
# 3. BASELINE MODELS (ALL BACKBONES)
# ==========================================

class FFNNClassifier(nn.Module):
    def __init__(self, input_size, sequence_length, hidden_size=64, num_classes=2):
        super().__init__()
        self.fc1 = nn.Linear(input_size * sequence_length, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        x = x.view(x.size(0), -1)
        out = self.relu(self.fc1(x))
        return self.fc2(out)

class RNNClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2, num_classes=2):
        super().__init__()
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        out, _ = self.rnn(x)
        return self.fc(out[:, -1, :])

class LSTMClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2, num_classes=2):
        super().__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])

class TCNClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_classes=2):
        super().__init__()
        self.conv = nn.Conv1d(in_channels=input_size, out_channels=hidden_size, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        x = x.transpose(1, 2)
        out = self.relu(self.conv(x))
        out, _ = torch.max(out, dim=2)
        return self.fc(out)

class TransformerClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_classes=2):
        super().__init__()
        self.embedding = nn.Linear(input_size, hidden_size)
        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_size, nhead=4, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=1)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        x = self.embedding(x)
        out = self.transformer(x)
        out = out.mean(dim=1)
        return self.fc(out)

# ==========================================
# 4. EVALUATION & TRAINING LOOP
# ==========================================

def evaluate_accuracy(model, X, y):
    model.eval()
    with torch.no_grad():
        X_tensor = torch.tensor(X, dtype=torch.float32)
        y_tensor = torch.tensor(y, dtype=torch.long)
        outputs = model(X_tensor)
        _, predicted = torch.max(outputs.data, 1)
        correct = (predicted == y_tensor).sum().item()
        accuracy = 100 * correct / len(y)
    return accuracy

def run_regime_pipeline():
    df = load_and_prepare_compound_data()
    
    # Feed all the new OHLCV-derived features into the neural network backbones
    features = ['SPY_Return', 'QQQ_Return', 'SPY_Log_Return', 'QQQ_Log_Return', 
                'SPY_Volume_Ratio', 'SPY_Intraday_Vol', 'QQQ_Intraday_Vol']
    scaler = StandardScaler()
    df[features] = scaler.fit_transform(df[features])
    
    seq_length = 30
    batch_size = 64
    epochs = 10
    
    train_data, val_data, test_data = create_sequences_and_split(df, features, 'Target_Regime', seq_length)
    X_train, y_train, _ = train_data
    X_val, y_val, _ = val_data
    X_test, y_test, _ = test_data
    
    print(f"Data Split -> Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")
    
    train_loader = DataLoader(TimeSeriesDataset(X_train, y_train), batch_size=batch_size, shuffle=True)
    
    models = {
        "FFNN/LR": FFNNClassifier(input_size=len(features), sequence_length=seq_length),
        "RNN": RNNClassifier(input_size=len(features)),
        "LSTM": LSTMClassifier(input_size=len(features)),
        "TCN": TCNClassifier(input_size=len(features)),
        "Transformer": TransformerClassifier(input_size=len(features))
    }
    
    results = []
    criterion = nn.CrossEntropyLoss()
    
    print("\n" + "="*60)
    print("--- Starting Backbone Comparison (Compound Regimes) ---")
    print("="*60)
    
    for name, model in models.items():
        print(f"Training {name} Backbone...")
        optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
        
        for epoch in range(epochs):
            model.train()
            for X_batch, y_batch in train_loader:
                optimizer.zero_grad()
                y_pred = model(X_batch)
                loss = criterion(y_pred, y_batch)
                loss.backward()
                optimizer.step()
                
        train_acc = evaluate_accuracy(model, X_train, y_train)
        val_acc = evaluate_accuracy(model, X_val, y_val)
        test_acc = evaluate_accuracy(model, X_test, y_test)
        
        results.append((name, train_acc, val_acc, test_acc))
        print(f"-> {name} | Train Acc: {train_acc:.1f}% | Val Acc: {val_acc:.1f}% | Test Acc: {test_acc:.1f}%\n")

    print("="*60)
    print(f"{'Backbone':<15} | {'Val Acc (2018-19)':<17} | {'Test Acc (2020+)':<15}")
    print("-" * 60)
    for name, train, val, test in sorted(results, key=lambda x: x[2], reverse=True):
        print(f"{name:<15} | {val:>15.2f}% | {test:>14.2f}%")
    print("="*60)

if __name__ == "__main__":
    run_regime_pipeline()